//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fall2020_CSC403_Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fall2020_CSC403_Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap battle_screen {
            get {
                object obj = ResourceManager.GetObject("battle_screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap battle_screen2 {
            get {
                object obj = ResourceManager.GetObject("battle_screen2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Boss_Villain_Belloq {
            get {
                object obj = ResourceManager.GetObject("Boss_Villain_Belloq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Boss_Villain_Dalek {
            get {
                object obj = ResourceManager.GetObject("Boss_Villain_Dalek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Boss_Villain_Dracula {
            get {
                object obj = ResourceManager.GetObject("Boss_Villain_Dracula", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enemy_cheetos {
            get {
                object obj = ResourceManager.GetObject("enemy_cheetos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enemy_koolaid {
            get {
                object obj = ResourceManager.GetObject("enemy_koolaid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enemy_poisonpacket {
            get {
                object obj = ResourceManager.GetObject("enemy_poisonpacket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream final_battle {
            get {
                return ResourceManager.GetStream("final_battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Amazo_versus_Belloq__mp3cut_net_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Amazo_versus_Belloq__mp3cut_net_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Amazo_versus_Dalek__mp3cut_net_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Amazo_versus_Dalek__mp3cut_net_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Amazo_versus_Dracula__mp3cut_net_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Amazo_versus_Dracula__mp3cut_net_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Corn_versus_Belloq__mp3cut_net___1_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Corn_versus_Belloq__mp3cut_net___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Corn_versus_Dalek__mp3cut_net_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Corn_versus_Dalek__mp3cut_net_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Corn_versus_Dracula__mp3cut_net_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Corn_versus_Dracula__mp3cut_net_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Mad_Hatter_versus_Belloq__mp3cut_net_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Mad_Hatter_versus_Belloq__mp3cut_net_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Mad_Hatter_versus_Dalek__mp3cut_net_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Mad_Hatter_versus_Dalek__mp3cut_net_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Mad_Hatter_versus_Dracula__mp3cut_net_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Mad_Hatter_versus_Dracula__mp3cut_net_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Minotaur_versus_Belloq__mp3cut_net_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Minotaur_versus_Belloq__mp3cut_net_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Minotaur_versus_Dalek__mp3cut_net_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Minotaur_versus_Dalek__mp3cut_net_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Minotaur_versus_Dracula__mp3cut_net_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Minotaur_versus_Dracula__mp3cut_net_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Sherlock_Holmes_versus_Belloq__mp3cut_net_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Sherlock_Holmes_versus_Belloq__mp3cut_net_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Sherlock_Holmes_versus_Dalek__mp3cut_net_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Sherlock_Holmes_versus_Dalek__mp3cut_net_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Sherlock_Holmes_versus_Dracula__mp3cut_net_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Sherlock_Holmes_versus_Dracula__mp3cut_net_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Winnie_the_Pooh_versus_Belloq__mp3cut_net_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Winnie_the_Pooh_versus_Belloq__mp3cut_net_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Winnie_the_Pooh_versus_Dalek__mp3cut_net_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Winnie_the_Pooh_versus_Dalek__mp3cut_net_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Final_Battle_Winnie_the_Pooh_versus_Dracula__mp3cut_net_ {
            get {
                return ResourceManager.GetStream("Final_Battle_Winnie_the_Pooh_versus_Dracula__mp3cut_net_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PickedPlayer {
            get {
                object obj = ResourceManager.GetObject("PickedPlayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pipe_Wall {
            get {
                object obj = ResourceManager.GetObject("Pipe_Wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player_Choice_1 {
            get {
                object obj = ResourceManager.GetObject("Player_Choice_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player_Choice_2 {
            get {
                object obj = ResourceManager.GetObject("Player_Choice_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player_Choice_3 {
            get {
                object obj = ResourceManager.GetObject("Player_Choice_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player_Choice_4 {
            get {
                object obj = ResourceManager.GetObject("Player_Choice_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player_Choice_5 {
            get {
                object obj = ResourceManager.GetObject("Player_Choice_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player_Choice_6 {
            get {
                object obj = ResourceManager.GetObject("Player_Choice_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stone_Wall {
            get {
                object obj = ResourceManager.GetObject("Stone_Wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Villain_Delgado_Master {
            get {
                object obj = ResourceManager.GetObject("Villain_Delgado_Master", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Villain_German_Mechanic {
            get {
                object obj = ResourceManager.GetObject("Villain_German_Mechanic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Villain_Invisible_Man {
            get {
                object obj = ResourceManager.GetObject("Villain_Invisible_Man", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Villain_Major_Toht {
            get {
                object obj = ResourceManager.GetObject("Villain_Major_Toht", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Villain_Mondasian_Cyberman {
            get {
                object obj = ResourceManager.GetObject("Villain_Mondasian_Cyberman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Villain_Wolfman {
            get {
                object obj = ResourceManager.GetObject("Villain_Wolfman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall {
            get {
                object obj = ResourceManager.GetObject("wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wood_Wall {
            get {
                object obj = ResourceManager.GetObject("Wood_Wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
